; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                = 10200331-x86_64 Linux             
[ DataSettings ]
datatype                           = snNucleotide                      
containsCodingNuc                  = False                             
MissingBaseSymbol                  = ?                                 
IdenticalBaseSymbol                = .                                 
GapSymbol                          = -                                 
Labelled Sites                     = All Sites                         
Labels to Include                  =                                   
[ ProcessTypes ]
ppInfer                            = true                              
ppNJ                               = true                              
[ AnalysisSettings ]
Analysis                           = Phylogeny Reconstruction          
Scope                              = All Selected Taxa                 
Statistical Method                 = Neighbor-joining                  
Phylogeny Test                     = ====================              
Test of Phylogeny                  = Bootstrap method                  
No. of Bootstrap Replications      = 1000                              
Substitution Model                 = ====================              
Substitutions Type                 = Nucleotide                        
Model/Method                       = Kimura 2-parameter model          
Substitutions to Include           = d: Transitions + Transversions    
Rates and Patterns                 = ====================              
Rates among Sites                  = Gamma Distributed (G)             
Gamma Parameter                    = 0.25                              
Pattern among Lineages             = Same (Homogeneous)                
Data Subset to Use                 = ====================              
Gaps/Missing Data Treatment        = Pairwise deletion                 
Site Coverage Cutoff (%)           = Not Applicable                    
System Resource Usage              = ====================              
Number of Threads                  = 2                                 
Has Time Limit                     = False                             
Maximum Execution Time             = -1                                
